### ISSUE TITLE
Parser RCPT TO

### ISSUE THREAD

**Issue by trtstm** [gopistolet/gopistolet#1]
als er geen email achter die TO komt returned de parser een RcptCmd. Zou eigenlijk een InvalidCmd moete returnen. InvalidCmd stuurt dan een SyntaxError naar de client. Denk eigenlijk dat het een SyntaxErrorParam moet zijn, maar daar hebbe wij geen cmd voor.

Edit: Er zijn wss nog zo'n gevallen

**Comment by DenBeke** [comment]
Oké, ja, ik moet er eens rustig unit tests voor schrijven...

**Comment by DenBeke** [comment]
Still todo...

**Comment by DenBeke** [comment]
`ParserLine()` moet dan geen error returnen maar gewoon een InvalidCommand?

**Comment by trtstm** [comment]
500 	Syntax error, command unrecognised
501 	Syntax error in parameters or arguments
502 	Command not implemented
504 	Command parameter not implemented

Just return a InvalidCmd if there is an error. That will send a SyntaxError back to the client. Don't know what the rfc says about which errors to return when. We could later add a field to the InvalidCmd to specify which error to send back.
