### ISSUE TITLE
Parser probleem met data

### ISSUE THREAD

**Issue by trtstm** [gopistolet/gopistolet#2]
Stel da ge deze cmds binnen krijgt:

	helo
	data
	test mail
	.
dan moet onze server na die data cmd al nen error geven dat er eerst een mail cmd moet zijn geweest.
Probleem is da de parser het geen dat erachter komt eerst parsed en dan pas een DataCmd returned.

We hebben zoiets nodig:

	type DataCmd struct {
		data DeferedContent
	}

	type DeferedContent struct {
		br *bufio.Reader
	}

	func (c *DeferedContent) GetContents() string {
		// lees en return hetgeen dat achter het data cmd komt.
	}

	cmd.data.getContents()

**Comment by DenBeke** [comment]
Ja, idd...
