### ISSUE TITLE
Blacklist could panic

### ISSUE THREAD

**Issue by DenBeke** [gopistolet/gopistolet#35]
Blacklist could panic on this:

```go
func (ns *Nixspam) CheckIp(ip string) bool {
	index := sort.SearchStrings(ns.IpList, ip)
	return ns.IpList[index] == ip
}
```

`index` could equal `len(ns.IpList)`.

> SearchStrings searches for x in a sorted slice of strings and returns the index as specified by Search. The return value is the index to insert x if x is not present (it could be len(a)). The slice must be sorted in ascending order.

**Comment by trtstm** [comment]
if index == len(ns.IpList) {
        return false
    }

?

**Comment by DenBeke** [comment]
Indeed, didn't have time to commit it...

**Comment by DenBeke** [comment]
Thanks, @trtstm
