### ISSUE TITLE
Don't handle empty lines/whitespace as commands

### ISSUE THREAD

**Issue by trtstm** [gopistolet/gopistolet#8]
When sending whitspace/newlines the parser creates smtp.UnknownCmd's.
The parser should just ignore whitespace.

**Comment by DenBeke** [comment]
Alright, I'll ignore empty lines...

**Comment by DenBeke** [comment]
Is this denoted in the RFC somewhere?

**Comment by trtstm** [comment]
No idea, try telnetting telenet and see what they do :p

**Comment by DenBeke** [comment]
Haha, that's how we check an RFC :D

**Comment by trtstm** [comment]
nvm they also give a command not recognized error

**Comment by DenBeke** [comment]
RFC doesn't say anything about ignoring empty lines or lines with useless content. I think it's good practice to return a `UnknownCmd` or `InvalidCmd` object in the parser. No need for change. (imo)
